### ISSUE TITLE
Serve should watch for changes and autorestart

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/elsa#8]
It's really poor developer experience to have to restart it manually.

**Comment by encukou** [comment]
You need to set `app.config['TEMPLATES_AUTO_RELOAD'] = True`, as in any Flask app.

The problem is that you need to set it before the Jinja environment is created, and helpers like `@app.template_filter` create the env.

Elsa does set the config variable. But by the time Elsa has a chance run, it may be too late for it to have any effect.

**Comment by encukou** [comment]
Don't know how to fix this properly. Perhaps making people use `from elsa import App` instead of `from flask import Flask`? (cc @hroncok)

**Comment by encukou** [comment]
This is reported in Flask: https://github.com/pallets/flask/issues/1907
